### ISSUE TITLE
error while trying to deploy to heroku

### ISSUE THREAD

**Issue by tasdikrahman** [ytamura/thorn-hackathon#1]
Hey @ytamura 

I am trying to deploy this app for [https://github.com/ytamura/thorn-hackathon.git](https://github.com/ytamura/thorn-hackathon.git) by setting the buildpack by doing a `heroku config:set BUILDPACK_URL=git://github.com/Azure-Vani/heroku-buildpack-opencv3.git`

I am getting the following error

```
Counting objects: 6, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 602 bytes | 0 bytes/s, done.
Total 6 (delta 5), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Python + OpenCV + Numpy + Scipy app detected
remote: -----> Generating environment
remote:        Unpacking...
remote: -----> Found requirements.txt, installing dependencies using pip
remote: Traceback (most recent call last):
remote:   File "/app/.heroku/python/bin/pip", line 7, in <module>
remote:     from pip import main
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/__init__.py", line 10, in <module>
remote:     from pip.util import get_installed_distributions, get_prog
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/util.py", line 18, in <module>
remote:     from pip._vendor.distlib import version
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/version.py", line 14, in <module>
remote:     from .compat import string_types
remote:   File "/app/.heroku/python/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
remote:     from urllib2 import (Request, urlopen, URLError, HTTPError,
remote: ImportError: cannot import name HTTPSHandler
remote: -----> Creating environment variables.
remote: -----> Buildpack installed.
remote: -----> Discovering process types
remote:        Procfile declares types -> web
remote: 
remote: -----> Compressing...
remote:        Done: 160.8M
remote: -----> Launching...
remote:        Released v13
remote:        https://thorn.herokuapp.com/ deployed to Heroku
remote: 
remote: Verifying deploy... done.
To https://git.heroku.com/thorn.git
 + e3d4f7b...a143ca1 master -> master (forced update)
```

Any help on that?

**Comment by ytamura** [comment]
Hi, I don't think this is an error specific to this project (which I'm not maintaining at all, btw...).  Maybe you can find some help here: http://stackoverflow.com/questions/20688034/importerror-cannot-import-name-httpshandler-using-pip
